apiVersion: v1
kind: ConfigMap
data:
  credentials: |-
    [profile oraculi-account]
    region = eu-central-1
    role_arn = arn:aws:iam::602887012891:role/AWSEKSKomiserRole
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token

    [profile jakes-account]
    region = eu-central-1
    role_arn = arn:aws:iam::890753381703:role/komiserRole
    source_profile = oraculi-account
    role_session_name = xactarget
metadata:
  annotations:
    meta.helm.sh/release-name: komiser-helm
    meta.helm.sh/release-namespace: komiser
  labels:
    app.kubernetes.io/managed-by: Helm
  name: aws-configmap
  namespace: komiser
