apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-configmap-credentials
data:
  credentials.yaml: |-
    [default]
    region = eu-central-1
    aws_access_key_id = YOUR-ACCESS-KEY-ID
    aws_secret_access_key = YOUR-SECRET-ACCESS-KEY