apiVersion: v1
kind: ConfigMap
metadata:
  name: komiser
data:
  config.toml: |
    [[aws]]
    name="Admin-Account"
    source="CREDENTIALS_FILE" # additionally EVIRONMENT_VARIABLES can be used
    path="./aws/credentials" # remove line if using ENVIRONMENT VARIABLES
    profile="Admin-Account" 

    [[aws]]
    name="Jakes-Account"
    source="CREDENTIALS_FILE" # additionally EVIRONMENT_VARIABLES can be used
    path="./aws/credentials" # remove line if using ENVIRONMENT VARIABLES
    profile="Jakes-Account"

    [sqlite]
    file="komiser.db"

    # Alternative data persistance option using postgresql DB
    # [postgres]
    # uri="postgres://postgres:komiser@localhost:5432/komiser?sslmode=disable"

  credentials: | 
    [Admin-Account]
    region=eu-central-1
    role_arn=arn:aws:iam::602887012891:role/komiser-multiple-cloud-account-demo 
    web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
  
    #[Jakes-Account]
    #region=eu-central-1
    #role_arn=arn:aws:iam::890753381703:role/komiser-role-test
    #source_profile="Admin-Account"
