apiVersion: v1
kind: ConfigMap
metadata:
  name: komiser
data:
  config.toml: |-
    [[aws]]
    name="Admin-Account"
    source="CREDENTIALS_FILE" # additionally EVIRONMENT_VARIABLES can be used
    path="./credentials.toml" # remove line if using ENVIRONMENT VARIABLES 
    profile="default"

    [[aws]]
    name="Jakes-Account"
    source="CREDENTIALS_FILE" # additionally EVIRONMENT_VARIABLES can be used
    path="./credentials.toml" # remove line if using ENVIRONMENT VARIABLES
    profile="jakes"

    [sqlite]
    file="komiser.db"

    # Alternative data persistance option using postgresql DB
    # [postgres]
    # uri="postgres://postgres:komiser@localhost:5432/komiser?sslmode=disable"

  credentials.toml: |- 
    [default]
    region=eu-central-1
    role_arn=arn:aws:iam::602887012891:role/komiser-multiple-cloud-account-demo 
    web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
  
    [jakes]
    region=eu-central-1
    role_arn=arn:aws:iam::890753381703:role/komiserRole 
    source_profile="default"