apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: komiser
spec:
  selector: 
    matchLabels: 
      app: komiser
  template: 
    metadata: 
      name: komiser
      labels: 
        app: komiser
    spec:
      serviceAccountName: komiser
      containers: 
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["--multiple"]
          env:
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.aws.region }}"