apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: komiser
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    matchLabels: 
      app: komiser
  template: 
    metadata: 
      name: komiser
    spec:
      containers: 
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
           env:
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.aws.region }}"