apiVersion: v1
kind: PersistentVolume
metadata:
  name: komiser-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  hostPath:
    path: "/mnt/storage"