apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komiser-pv-claim
  namespace: testing-komiser
spec:
  storageClassName: gp3
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 5Gi
