apiVersion: v1
kind: ServiceAccount
metadata:
  name: komiser
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::602887012891:role/AWSEKSKomiserRole
    #eks.amazonaws.com/role-arn: arn:aws:iam::890753381703:role/komiserRole